module.exports = {
  subgraph: [
    { type: "doc", id: "subgraph" },
    { type: "doc", id: "playground" },
    {
      type: "category",
      label: "Examples",
      // collapsed: false,
      items: [
        { type: "doc", id: "examples/fees" },
        { type: "doc", id: "examples/epochs" },
        { type: "doc", id: "examples/24h-fees" },
      ],
    },
    // { type: "doc", id: "subgraph/api" },
    {
      type: "category",
      label: "API Reference",
      items: [
        {
          type: "category",
          label: "Entities",
          items: [
            "subgraph/objects/asset",
            "subgraph/objects/asset-amount",
            "subgraph/objects/darknode",
            "subgraph/objects/epoch",
            "subgraph/objects/integrator",
            "subgraph/objects/integrator-contract",
            "subgraph/objects/meta",
            "subgraph/objects/ren-vm",
            "subgraph/objects/transaction",
            "subgraph/objects/value-with-asset",
          ],
        },
        {
          type: "category",
          label: "Other",
          items: [
            {
              type: "category",
              label: "Queries",
              items: [
                "subgraph/queries/asset",
                "subgraph/queries/asset-amount",
                "subgraph/queries/asset-amounts",
                "subgraph/queries/assets",
                "subgraph/queries/darknode",
                "subgraph/queries/darknodes",
                "subgraph/queries/epoch",
                "subgraph/queries/epoches",
                "subgraph/queries/integrator",
                "subgraph/queries/integrator-contract",
                "subgraph/queries/integrator-contracts",
                "subgraph/queries/integrators",
                "subgraph/queries/meta",
                "subgraph/queries/ren-v-ms",
                "subgraph/queries/ren-vm",
                "subgraph/queries/transaction",
                "subgraph/queries/transactions",
                "subgraph/queries/value-with-asset",
                "subgraph/queries/value-with-assets",
              ],
            },
            {
              type: "category",
              label: "Subscriptions",
              items: [
                "subgraph/subscriptions/asset",
                "subgraph/subscriptions/asset-amount",
                "subgraph/subscriptions/asset-amounts",
                "subgraph/subscriptions/assets",
                "subgraph/subscriptions/darknode",
                "subgraph/subscriptions/darknodes",
                "subgraph/subscriptions/epoch",
                "subgraph/subscriptions/epoches",
                "subgraph/subscriptions/integrator",
                "subgraph/subscriptions/integrator-contract",
                "subgraph/subscriptions/integrator-contracts",
                "subgraph/subscriptions/integrators",
                "subgraph/subscriptions/meta",
                "subgraph/subscriptions/ren-v-ms",
                "subgraph/subscriptions/ren-vm",
                "subgraph/subscriptions/transaction",
                "subgraph/subscriptions/transactions",
                "subgraph/subscriptions/value-with-asset",
                "subgraph/subscriptions/value-with-assets",
              ],
            },
            {
              type: "category",
              label: "Directives",
              items: [
                "subgraph/directives/deprecated",
                "subgraph/directives/derived-from",
                "subgraph/directives/entity",
                "subgraph/directives/include",
                "subgraph/directives/skip",
                "subgraph/directives/specified-by",
                "subgraph/directives/subgraph-id",
              ],
            },
            {
              type: "category",
              label: "Enums",
              items: [
                "subgraph/enums/asset-amount-order-by",
                "subgraph/enums/asset-order-by",
                "subgraph/enums/darknode-order-by",
                "subgraph/enums/epoch-order-by",
                "subgraph/enums/integrator-contract-order-by",
                "subgraph/enums/integrator-order-by",
                "subgraph/enums/order-direction",
                "subgraph/enums/ren-vm-order-by",
                "subgraph/enums/subgraph-error-policy",
                "subgraph/enums/transaction-order-by",
                "subgraph/enums/transaction-type",
                "subgraph/enums/value-with-asset-order-by",
              ],
            },
            {
              type: "category",
              label: "Inputs",
              items: [
                "subgraph/inputs/asset-amount-filter",
                "subgraph/inputs/asset-filter",
                "subgraph/inputs/block-height",
                "subgraph/inputs/darknode-filter",
                "subgraph/inputs/epoch-filter",
                "subgraph/inputs/integrator-contract-filter",
                "subgraph/inputs/integrator-filter",
                "subgraph/inputs/ren-vm-filter",
                "subgraph/inputs/transaction-filter",
                "subgraph/inputs/value-with-asset-filter",
              ],
            },
            {
              type: "category",
              label: "Scalars",
              items: [
                "subgraph/scalars/big-decimal",
                "subgraph/scalars/big-int",
                "subgraph/scalars/boolean",
                "subgraph/scalars/bytes",
                "subgraph/scalars/id",
                "subgraph/scalars/int",
                "subgraph/scalars/string",
              ],
            },
          ],
        },
      ],
    },
  ],
};
